#!/bin/bash

if [ $(pidof -x dashboard| wc -w) -gt 2 ]; then 
    echo "More than 1 instance"
    exit
fi

SOURCE_PATH="`dirname \"$0\"`"
export CCACHE_DIR="/home/builder/.ccache"

cd "$SOURCE_PATH/build"
xvfb-run -a -n 11 ctest -D Continuous && (kill `cat $LIVE_DIRECTORY/bin/novastory.pid`; make install; "$LIVE_DIRECTORY/bin/novastory_server" -d)
