#!/bin/bash

if [ $(/usr/sbin/pidof -x dashboard| wc -w) -gt 2 ]; then 
    echo "More than 1 instance"
    exit
fi

SOURCE_PATH="`dirname \"$0\"`"
export CCACHE_DIR="/home/builder/.ccache"

cd "$SOURCE_PATH/build"
xvfb-run -a -n 11 ctest -D Continuous && make install
