#!/bin/bash

if [ $(pidof -x dashboard| wc -w) -gt 2 ]; then 
    echo "More than 1 instance"
    exit
fi

SOURCE_PATH="`dirname \"$0\"`"
export CCACHE_DIR="~/.ccache"

cd "$SOURCE_PATH/testing"
xvfb-run -a -n 11 ctest -D Continuous
