#!/bin/bash

LIVE_DIRECTORY="/home/builder/projects/novastory/live"

SOURCE_PATH=$(dirname $(realpath -s $0))
cd $SOURCE_PATH
REVISION=`git log --pretty=format:'' | wc -l`
DESCRIBE=`git describe`

if [ $(pidof -x fedoralive| wc -w) -gt 2 ]; then 
    echo "More than 1 instance"
    exit
fi

SUBFOLDER="r$REVISION"
if [ $DESCRIBE ]; then
	SUBFOLDER="r$REVISION ($DESCRIBE)"
fi


if [ $REVISION -le 0 ]; then
	echo "Unknown revision"
	exit
fi

if [ ! -d "$LIVE_DIRECTORY/$SUBFOLDER" ]; then
	echo "New revision founded"
	export CCACHE_DIR="/home/builder/.ccache"
	rm -fr build
	mkdir build
	cd build
	mkdir "$LIVE_DIRECTORY/$SUBFOLDER"
	cmake -DWITH_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$LIVE_DIRECTORY/$SUBFOLDER" ../
	make -j4
	make test
	if [ $? -eq 0 ]; then
		make install
		rm -f $LIVE_DIRECTORY/current
		ln -s "$LIVE_DIRECTORY/$SUBFOLDER" "$LIVE_DIRECTORY/current"
	else
		echo "tests not passed"
	fi
fi

echo "All done"