#!/bin/bash

UPLOAD_DIRECTORY="/home/builder/public_html/novastory"

SOURCE_PATH=$(dirname $(realpath -s $0))
cd $SOURCE_PATH
REVISION=`git log --pretty=format:'' | wc -l`
DESCRIBE=`git describe`

if [ $(pidof -x fedorawinbuild| wc -w) -gt 2 ]; then 
    echo "More than 1 instance"
    exit
fi

SUBFOLDER="r$REVISION"
if [ $DESCRIBE ]; then
	SUBFOLDER="r$REVISION ($DESCRIBE)"
fi


if [ $REVISION -le 0 ]; then
	echo "Unknown revision"
	exit
fi

if [ ! -d "$UPLOAD_DIRECTORY/$SUBFOLDER" ]; then
	echo "New revision founded"
	rm -fr win32build
	mkdir win32build
	cd win32build
	mingw64-cmake -DWITH_TESTS=ON -DFEDORA_CROSSCOMPILATION=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$SOURCE_PATH/win32build/final" ../
	mingw64-make -j2
	mingw64-make install
	zip -r novastory.zip final/
	mkdir $UPLOAD_DIRECTORY/$SUBFOLDER
	chcon --type=httpd_user_content_t novastory.zip
	mv novastory.zip $UPLOAD_DIRECTORY/$SUBFOLDER/
fi

echo "All done"