#ifndef CONFIG_H
#define CONFIG_H

#define RECAPTCHA_PUBLIC_KEY "6LfjsO4SAAAAADEhNeb51KeXPpVu_vtFQRC0w4iO"
#define RECAPTCHA_PRIVATE_KEY "6LfjsO4SAAAAAOlX0CmwHqWtaqUmftDha4PUmXQ2"

#endif // RAWFILEHANDLER_H
